version: '3'
services:
  mongo-server:
    image: mongo
    restart: always
  node-app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - MONGO_HOST=mongo-server
      - MONGO_PORT=27017
      - MONGO_DB=test
      - PORT=3000
    command: npm run watch
